import { InferOutput, object, string } from 'valibot';

export const EstadoFederalSchema = object({
  codigo: string(),
  nombre: string(),
});
export type EstadoFederal = InferOutput<typeof EstadoFederalSchema>;

export enum EstadosDeVenezuela {
  AMAZONAS = 1,
  ANZOATEGUI,
  APURE,
  ARAGUA,
  BARINAS,
  BOLIVAR,
  CARABOBO,
  COJEDES,
  DELTA_AMACURO,
  DISTRITO_CAPITAL,
  FALCON,
  GUARICO,
  LA_GUAIRA,
  LARA,
  MERIDA,
  MIRANDA,
  MONAGAS,
  NUEVA_ESPARTA,
  PORTUGUESA,
  SUCRE,
  TACHIRA,
  TRUJILLO,
  YARACUY,
  ZULIA,
}

/**
 * **ISO 3166-2:VE**
 * es la entrada para Venezuela en ISO 3166-2, parte de los códigos de normalización ISO 3166 publicados por la Organización Internacional de Normalización (ISO), que define los códigos para los nombres de las principales subdivisiones (p.ej., provincias o estados) de todos los países codificados en ISO 3166-1.
 * @link https://es.wikipedia.org/wiki/ISO_3166-2:VE
 */
export enum EstadosDeVenezuelaISO {
  AMAZONAS = 'VE-Z',
  ANZOATEGUI = 'VE-B',
  APURE = 'VE-C',
  ARAGUA = 'VE-D',
  BARINAS = 'VE-E',
  BOLIVAR = 'VE-F',
  CARABOBO = 'VE-G',
  COJEDES = 'VE-H',
  DELTA_AMACURO = 'VE-Y',
  DISTRITO_CAPITAL = 'VE-A',
  FALCON = 'VE-I',
  GUARICO = 'VE-J',
  LA_GUAIRA = 'VE-X',
  LARA = 'VE-K',
  MERIDA = 'VE-L',
  MIRANDA = 'VE-M',
  MONAGAS = 'VE-N',
  NUEVA_ESPARTA = 'VE-O',
  PORTUGUESA = 'VE-P',
  SUCRE = 'VE-R',
  TACHIRA = 'VE-S',
  TRUJILLO = 'VE-T',
  YARACUY = 'VE-U',
  ZULIA = 'VE-V',
}

export enum EstadosDeVenezuelaCNE {
  DISTRITO_CAPITAL = 1,
  ANZOATEGUI,
  APURE,
  ARAGUA,
  BARINAS,
  BOLIVAR,
  CARABOBO,
  COJEDES,
  FALCON,
  GUARICO,
  LARA,
  MERIDA,
  MIRANDA,
  MONAGAS,
  NUEVA_ESPARTA,
  PORTUGUESA,
  SUCRE,
  TACHIRA,
  TRUJILLO,
  YARACUY,
  ZULIA,
  AMAZONAS,
  DELTA_AMACURO,
  LA_GUAIRA,
}

export const ESTADOS_FEDERALES = [
  { codigo: 'VE-Z', nombre: 'Amazonas' },
  { codigo: 'VE-B', nombre: 'Anzoategui' },
  { codigo: 'VE-C', nombre: 'Apure' },
  { codigo: 'VE-D', nombre: 'Aragua' },
  { codigo: 'VE-E', nombre: 'Barinas' },
  { codigo: 'VE-F', nombre: 'Bolivar' },
  { codigo: 'VE-G', nombre: 'Carabobo' },
  { codigo: 'VE-H', nombre: 'Cojedes' },
  { codigo: 'VE-Y', nombre: 'Delta Amacuro' },
  { codigo: 'VE-A', nombre: 'Distrito Capital' },
  { codigo: 'VE-I', nombre: 'Falcon' },
  { codigo: 'VE-J', nombre: 'Guarico' },
  { codigo: 'VE-X', nombre: 'La Guaira' },
  { codigo: 'VE-K', nombre: 'Lara' },
  { codigo: 'VE-L', nombre: 'Merida' },
  { codigo: 'VE-M', nombre: 'Miranda' },
  { codigo: 'VE-N', nombre: 'Monagas' },
  { codigo: 'VE-O', nombre: 'Nueva Esparta' },
  { codigo: 'VE-P', nombre: 'Portuguesa' },
  { codigo: 'VE-R', nombre: 'Sucre' },
  { codigo: 'VE-S', nombre: 'Tachira' },
  { codigo: 'VE-T', nombre: 'Trujillo' },
  { codigo: 'VE-U', nombre: 'Yaracuy' },
  { codigo: 'VE-V', nombre: 'Zulia' },
] as const;
