export * from './obtener_areas_de_formacion.usecase';
export * from './obtener_busqueda_rapida.usecase';
export * from './obtener_cantidad_de_estudiantes.usecase';
export * from './obtener_cantidad_de_estudiantes_por_nivel_academico.usecase';
export * from './obtener_niveles_academicos.usecase';
export * from './obtener_pensum.usecase';
export * from './obtener_persona.usecase';
export * from './obtener_registros_recientes.usecase';
export * from './obtener_seccion_academica.usecase';
