theme: minima
title: SWAI
description: Documentación oficial de SWAI sistema web
author:
  name: Sanaruca
  email: 'sanaruca@gmail.com'

# Navegación personalizada
header_pages:
  - index.md
  - instalacion_tecnica.md

minima:
  social_links:
    - title: GitHub
      icon: github
      url: 'https://github.com/sanaruca'
