theme: minima
title: SWAI
description: Manual de instalación de SWAI sistema web
site:
  author:
    name: Sanaruca
    email: 'sanaruca@gmail.com'

# Navegación personalizada
header_pages:
  - instalacion_tecnica.md
  - instalacion_con_installer.md

minima:
  navigation:
    - instalacion_tecnica.md
    - instalacion_con_installer.md
  social_links:
    - title: GitHub
      icon: github
      url: 'https://github.com/Sanaruca'
