export * from './tipo_de_estudiante.tag.component';
export * from './tipo_de_espacio_academico.tag.component';
export * from './tipo_de_empleado.tag.component';
export * from './sexo.tag.component';
export * from './seccion.tag.component';
export * from './nivel_academico.tag.component';
export * from './illustration.component';
export * from './estado_de_un_recurso.tag.component';
export * from './estado_academico.tag.component';
